# Generated by Django 5.2.3 on 2025-06-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
